name: Create release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip Folder
        run: cd USA_platforms; zip -r USA_platforms.zip Platforms

      - name: Zip Folder
        run: cd WORLD_platforms; zip -r JAPAN_platforms.zip Platforms

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./USA_platforms/USA_platforms.zip
            ./JAPAN_platforms/JAPAN_platforms.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
